// Static role -> permission-string map, ported from Hala's
// frontend/src/lib/permissions.ts (see hala-audit/frontend/src/lib/permissions.ts).
// The backend is the source of truth for authorization; the frontend has its
// own copy (frontend/src/lib/permissions.ts) purely for conditional UI
// rendering (hide/disable), never for enforcement.

export const PERMISSIONS = {
  LEADS_VIEW: 'leads:view',
  LEADS_CREATE: 'leads:create',
  LEADS_EDIT: 'leads:edit',
  LEADS_DELETE: 'leads:delete',
  LEADS_ASSIGN: 'leads:assign',
  LEADS_EXPORT: 'leads:export',

  CUSTOMERS_VIEW: 'customers:view',
  CUSTOMERS_CREATE: 'customers:create',
  CUSTOMERS_EDIT: 'customers:edit',
  CUSTOMERS_DELETE: 'customers:delete',

  QUOTATIONS_VIEW: 'quotations:view',
  QUOTATIONS_CREATE: 'quotations:create',
  QUOTATIONS_EDIT: 'quotations:edit',
  QUOTATIONS_DELETE: 'quotations:delete',
  QUOTATIONS_APPROVE: 'quotations:approve',
  QUOTATIONS_SEND: 'quotations:send',

  BOOKINGS_VIEW: 'bookings:view',
  BOOKINGS_CREATE: 'bookings:create',
  BOOKINGS_EDIT: 'bookings:edit',
  BOOKINGS_CANCEL: 'bookings:cancel',

  FINANCE_VIEW: 'finance:view',
  FINANCE_COLLECT_PAYMENT: 'finance:collect_payment',
  FINANCE_APPROVE_REFUND: 'finance:approve_refund',
  FINANCE_REPORTS: 'finance:reports',

  VENDORS_VIEW: 'vendors:view',
  VENDORS_CREATE: 'vendors:create',
  VENDORS_EDIT: 'vendors:edit',

  PACKAGES_VIEW: 'packages:view',
  PACKAGES_CREATE: 'packages:create',
  PACKAGES_EDIT: 'packages:edit',
  PACKAGES_DELETE: 'packages:delete',

  TASKS_VIEW: 'tasks:view',
  TASKS_CREATE: 'tasks:create',
  TASKS_EDIT: 'tasks:edit',
  TASKS_DELETE: 'tasks:delete',

  MASTERS_VIEW: 'masters:view',
  MASTERS_MANAGE: 'masters:manage',

  OPERATIONS_VIEW: 'operations:view',
  OPERATIONS_MANAGE: 'operations:manage',

  REPORTS_VIEW: 'reports:view',
  REPORTS_EXPORT: 'reports:export',

  SETTINGS_BRANCHES: 'settings:branches',
  SETTINGS_ROLES: 'settings:roles',
  SETTINGS_USERS: 'settings:users',

  HR_VIEW: 'hr:view',
  HR_MANAGE: 'hr:manage',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

export type RoleName =
  | 'super_admin'
  | 'branch_manager'
  | 'sales_manager'
  | 'sales_executive'
  | 'operations_manager'
  | 'operations_executive'
  | 'accounts_manager'
  | 'accounts_executive'
  | 'marketing_executive'
  | 'hr_executive'
  | 'support_staff';

export const ROLE_PERMISSIONS: Record<RoleName, Permission[]> = {
  super_admin: ALL_PERMISSIONS,

  branch_manager: ALL_PERMISSIONS.filter(
    (p) => p !== PERMISSIONS.SETTINGS_ROLES && p !== PERMISSIONS.SETTINGS_USERS,
  ),

  sales_manager: [
    PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.LEADS_DELETE, PERMISSIONS.LEADS_ASSIGN, PERMISSIONS.LEADS_EXPORT,
    PERMISSIONS.CUSTOMERS_VIEW, PERMISSIONS.CUSTOMERS_CREATE, PERMISSIONS.CUSTOMERS_EDIT,
    PERMISSIONS.CUSTOMERS_DELETE,
    PERMISSIONS.QUOTATIONS_VIEW, PERMISSIONS.QUOTATIONS_CREATE, PERMISSIONS.QUOTATIONS_EDIT,
    PERMISSIONS.QUOTATIONS_DELETE, PERMISSIONS.QUOTATIONS_APPROVE, PERMISSIONS.QUOTATIONS_SEND,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.MASTERS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.PACKAGES_VIEW, PERMISSIONS.PACKAGES_CREATE, PERMISSIONS.PACKAGES_EDIT,
  ],

  sales_executive: [
    PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE, PERMISSIONS.LEADS_EDIT,
    PERMISSIONS.QUOTATIONS_VIEW, PERMISSIONS.QUOTATIONS_CREATE, PERMISSIONS.QUOTATIONS_EDIT,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.MASTERS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.PACKAGES_VIEW,
  ],

  operations_manager: [
    PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_CREATE, PERMISSIONS.BOOKINGS_EDIT,
    PERMISSIONS.BOOKINGS_CANCEL,
    PERMISSIONS.VENDORS_VIEW, PERMISSIONS.VENDORS_CREATE, PERMISSIONS.VENDORS_EDIT,
    PERMISSIONS.MASTERS_VIEW, PERMISSIONS.MASTERS_MANAGE,
    PERMISSIONS.OPERATIONS_VIEW, PERMISSIONS.OPERATIONS_MANAGE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
    PERMISSIONS.PACKAGES_VIEW, PERMISSIONS.PACKAGES_CREATE, PERMISSIONS.PACKAGES_EDIT,
    PERMISSIONS.PACKAGES_DELETE,
  ],

  operations_executive: [
    PERMISSIONS.BOOKINGS_VIEW, PERMISSIONS.BOOKINGS_EDIT,
    PERMISSIONS.MASTERS_VIEW,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
  ],

  accounts_manager: [
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_COLLECT_PAYMENT,
    PERMISSIONS.FINANCE_APPROVE_REFUND, PERMISSIONS.FINANCE_REPORTS,
    PERMISSIONS.REPORTS_VIEW, PERMISSIONS.REPORTS_EXPORT,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
  ],

  accounts_executive: [
    PERMISSIONS.FINANCE_VIEW, PERMISSIONS.FINANCE_COLLECT_PAYMENT,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
  ],

  marketing_executive: [
    PERMISSIONS.LEADS_VIEW, PERMISSIONS.LEADS_CREATE,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
  ],

  hr_executive: [
    PERMISSIONS.HR_VIEW, PERMISSIONS.HR_MANAGE,
  ],

  support_staff: [
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.CUSTOMERS_VIEW,
    PERMISSIONS.BOOKINGS_VIEW,
    PERMISSIONS.QUOTATIONS_VIEW,
    PERMISSIONS.FINANCE_VIEW,
    PERMISSIONS.VENDORS_VIEW,
    PERMISSIONS.OPERATIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.TASKS_VIEW, PERMISSIONS.TASKS_CREATE, PERMISSIONS.TASKS_EDIT,
  ],
};

export function roleHasPermission(role: string | undefined, permission: Permission): boolean {
  if (!role) return false;
  const perms = ROLE_PERMISSIONS[role as RoleName];
  return !!perms && perms.includes(permission);
}
